### ISSUE TITLE
Potential security loophole when proxying with wrong config

### ISSUE THREAD

**Issue by brightzheng100** [clastix/capsule-proxy#156]
This is not a vulnerability report even the title sounds like that.

Let me walk it through the process and you'll know why I say that.

## 1. Launch the `capsule-proxy`:

Walk through the steps by following the doc to prepare the below stuff:
- Deploy Capsule
- Generate TLS cert/key by `mkcert`

Then launch the `capsule-proxy` outside of the cluster (it would be the same if you launch it in cluster):
```sh
$ go run . \
  --ssl-cert-path=localhost.pem \
  --ssl-key-path=localhost-key.pem \
  --zap-log-level=10 \
  --enable-ssl=false
```

Please note here that we intentionally disable the TLS with `--enable-ssl=false` as this is the key point.

## 2. Update `alice`'s kubeconfig file

Let assume you've created a Tenant named `gas` and generated `alice`'s kubeconfig by following `Capsule`'s doc.

Now we make a copy of it and rename it as ``, with below update:

```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: <OMITTED>
    server: http://localhost:9001
  name: kind-kind-capsule
contexts:
- context:
    cluster: kind-kind-capsule
    user: alice
  name: alice-gas
current-context: alice-gas
kind: Config
preferences: {}
users:
- name: alice
  user:
    client-certificate: alice-gas.crt
    client-key: alice-gas.key
```

Note the `server: http://localhost:9001` part.

## 3. Have a try:

```sh
# Without proxy, alice can't get namespaces, as expected in K8s
$ KUBECONFIG=alice-gas.kubeconfig kg ns
Error from server (Forbidden): namespaces is forbidden: User "alice" cannot list resource "namespaces" in API group "" at the cluster scope

# With the proxy, alice CAN list all namespaces which is far away from what she should be granted
$ KUBECONFIG=alice-gas-proxy.kubeconfig kg ns
NAME                 STATUS   AGE
capsule-system       Active   25h
default              Active   25h
gas-dev              Active   25h
kube-node-lease      Active   25h
kube-public          Active   25h
kube-system          Active   25h
local-path-storage   Active   25h
```

Note that she should be granted ONLY `gas-dev` namespace in a proxied `kubectl get ns`.
