### ISSUE TITLE
Providing proxy capabilities to other users or groups

### ISSUE THREAD

**Issue by prometherion** [clastix/capsule-proxy#196]
# User story

With the current design of Capsule, specific permissions are granted to Tenant Owners like listing Tenant resources, such as Priority, Ingress, Storage Classes, or Nodes.

This is possible thanks to the `proxySettings` section of each Tenant Owner.

```yaml
apiVersion: capsule.clastix.io/v1beta1
kind: Tenant
metadata:
  name: solar
spec:
  owners:
  - kind: User
    name: alice
    proxySettings:
    - kind: Nodes
      operations:
      - List
```

If the cluster-admin would like to provide access to the Tenant nodes to a set of users (e.g.: group named `sre`) the unique way to achieving this would be assigning the Tenant ownership to this group, providing a privilege too wide and out of the desired scope.

# Solution

`capsule-proxy` should introduce a CRD in order to control which extra users would be able to perform some set of operations on the Tenant resources, without polluting the multi-tenancy design with limited roles to a subset of users.

The proposed CRD could be the following.

```yaml
apiVersion: capsule.clastix.io/v1beta1
kind: ProxySettings
metadata:
  name: sre-readers
  namespace: solar-management
spec:
  subjects:
  - name: sre
    kind: Group
    proxySettings:
    - kind: Nodes
      operations:
      - List
```

- The `ProxySetting` resource will be Namespace-scoped: when deployed into a Tenant Namespace that will provide subjects the declared capabilities to the Tenant which the Namespace is belonging
- `subjects` will use the same Capsule's `OwnerRef` structure to have the same object and simplify implementation
- Being Namespace-scoped, these settings would be granted to Tenant Owners using the Capsule's `additionalRoleBinding` specification key

# Users that contributed to the design

- @MaxFedotov 
- @carpenterm
