### ISSUE TITLE
Disable Service Monitor installation from Helm Chart defaults

### ISSUE THREAD

**Issue by bsctl** [clastix/capsule-proxy#199]
Currently, the service monitor resource is installed by default with Helm Chart. However, if no monitoring stack is installed on the cluster (or it will be installed later), the corresponding CRD is not defined and the Chart installation fails.

`Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"`

```yaml
# ServiceMonitor
serviceMonitor:
  # -- Enable ServiceMonitor
  enabled: true <<< it should be false
```
