### ISSUE TITLE
Job kind immutability breaks gitops. capsule-proxy-certgen job must support ttlSecondsAfterFinished as a helm chart value

### ISSUE THREAD

**Issue by RoFz** [clastix/capsule-proxy#236]
Hello guys,

I'm not entirely sure if this is an actual feature request or a bug, but here it goes anyways.

Requested feature: 

- a helm chart value for capsule-proxy that would allow its capsule-proxy-certgen job to be excluded after it gets executed

Justification:

due to a k8s issue/characteristic?, we're unable to manage capsule-proxy using gitops (with flux). Every time flux needs to update the capsule-proxy helm chart, it fails due to the job being immutable:

kubectl get events:

> 0s          Warning   error                     helmrelease/capsule-proxy                  reconciliation failed: Helm upgrade failed: cannot patch "capsule-proxy-certgen" with kind Job: Job.batch "capsule-proxy-certgen" is invalid: spec.template: Invalid value: core.PodTemplateSpec{ObjectMeta:v1.ObjectMeta{Name:"capsule-proxy-certgen", GenerateName:"", Namespace:"", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string{"app.kubernetes.io/instance":"capsule-proxy", "app.kubernetes.io/managed-by":"Helm", "controller-uid":"1a09cd2f-edac-46f0-998b-34857780c5f9", "helm.sh/chart":"capsule-proxy-0.3.2", "job-name":"capsule-proxy-certgen"}, Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, Spec:core.PodSpec{Volumes:[]core.Volume(nil), InitContainers:[]core.Container(nil), Containers:[]core.Container{core.Container{Name:"post-install-job", Image:"docker.io/jettech/kube-webhook-certgen:v1.3.0", Command:[]string(nil), Args:[]string{"create", "--host=capsule-proxy.ops-capsule-001.svc,capsule-proxy", "--namespace=$(NAMESPACE)", "--secret-name=capsule-proxy", "--cert-name=tls.crt", "--key-name=tls.key"}, WorkingDir:"", Ports:[]core.ContainerPort(nil), EnvFrom:[]core.EnvFromSource(nil), Env:[]core.EnvVar{core.EnvVar{Name:"NAMESPACE", Value:"", ValueFrom:(*core.EnvVarSource)(0xc02b47ad20)}}, Resources:core.ResourceRequirements{Limits:core.ResourceList(nil), Requests:core.ResourceList(nil)}, VolumeMounts:[]core.VolumeMount(nil), VolumeDevices:[]core.VolumeDevice(nil), LivenessProbe:(*core.Probe)(nil), ReadinessProbe:(*core.Probe)(nil), StartupProbe:(*core.Probe)(nil), Lifecycle:(*core.Lifecycle)(nil), TerminationMessagePath:"/dev/termination-log", TerminationMessagePolicy:"File", ImagePullPolicy:"IfNotPresent", SecurityContext:(*core.SecurityContext)(nil), Stdin:false, StdinOnce:false, TTY:false}}, EphemeralContainers:[]core.EphemeralContainer(nil), RestartPolicy:"Never", TerminationGracePeriodSeconds:(*int64)(0xc028abd258), ActiveDeadlineSeconds:(*int64)(nil), DNSPolicy:"ClusterFirst", NodeSelector:map[string]string(nil), ServiceAccountName:"capsule-proxy", AutomountServiceAccountToken:(*bool)(nil), NodeName:"", SecurityContext:(*core.PodSecurityContext)(0xc00912c080), ImagePullSecrets:[]core.LocalObjectReference(nil), Hostname:"", Subdomain:"", SetHostnameAsFQDN:(*bool)(nil), Affinity:(*core.Affinity)(nil), SchedulerName:"default-scheduler", Tolerations:[]core.Toleration(nil), HostAliases:[]core.HostAlias(nil), PriorityClassName:"", Priority:(*int32)(nil), PreemptionPolicy:(*core.PreemptionPolicy)(nil), DNSConfig:(*core.PodDNSConfig)(nil), ReadinessGates:[]core.PodReadinessGate(nil), RuntimeClassName:(*string)(nil), Overhead:core.ResourceList(nil), EnableServiceLinks:(*bool)(nil), TopologySpreadConstraints:[]core.TopologySpreadConstraint(nil), OS:(*core.PodOS)(nil)}}: field is immutable

And this is the related k8s issue explaining the behavior above: [89657](https://github.com/kubernetes/kubernetes/issues/89657)

The suggested workaround - manually deleting the job before flux reconciliation - breaks the purpose of gitops, so it would be great if we could have capsule-proxy's helm chart to support the TTL mechanism for finished jobs, as mentioned [here](https://kubernetes.io/docs/concepts/workloads/controllers/job/#ttl-mechanism-for-finished-jobs). Like so:

```
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    meta.helm.sh/release-name: capsule-proxy
    meta.helm.sh/release-namespace: ops-capsule-001
  labels:
    app.kubernetes.io/instance: capsule-proxy
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: 0.3.0
    helm.sh/chart: capsule-proxy-0.3.1
    helm.toolkit.fluxcd.io/name: capsule-proxy
    helm.toolkit.fluxcd.io/namespace: flux-001
  name: capsule-proxy-certgen
  namespace: capsule-001
spec:
  backoffLimit: 6
  completionMode: NonIndexed
  completions: 1
  parallelism: 1
  selector:
    matchLabels:
      controller-uid: <uuid>
  suspend: false
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: capsule-proxy
        app.kubernetes.io/managed-by: Helm
        controller-uid: <uuid>
        helm.sh/chart: capsule-proxy-0.3.1
        job-name: capsule-proxy-certgen
      name: capsule-proxy-certgen
    spec:
      ttlSecondsAfterFinished: 0                <--- this here
      containers:
      - args:
        - create
        - --host=capsule-proxy.ops-capsule-001.svc,capsule-proxy
        - --namespace=$(NAMESPACE)
        - --secret-name=capsule-proxy
        - --cert-name=tls.crt
        - --key-name=tls.key
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: docker.io/jettech/kube-webhook-certgen:v1.3.0
        imagePullPolicy: IfNotPresent
        name: post-install-job
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: capsule-proxy
      serviceAccountName: capsule-proxy
      terminationGracePeriodSeconds: 30
```

Temporarily we'll address this via flux's helm post renderers, but it would be great to have this natively supported by capsule-proxy's helm chart. It would save people the trouble of doing custom post-processing tweaks.

Cheers
