### ISSUE TITLE
User or group with LIST permission is able to create object

### ISSUE THREAD

**Issue by MaxFedotov** [clastix/capsule-proxy#242]
# Bug description

Tenant owner with `list` permissions on object is able to create them

# How to reproduce

create an owner with following permissions
```
  owners:
  - kind: Group
    name: foo
    proxySettings:
    - kind: IngressClasses
      operations:
      - List
    - kind: Nodes
      operations:
      - List
    - kind: StorageClasses
      operations:
      - List
```

User will be able to `create` ingress\storage class, although having only `list` permissions

# Expected behavior

An error should be returned to user
