### ISSUE TITLE
Group Impersenation Handling

### ISSUE THREAD

**Issue by oliverbaehler** [clastix/capsule-proxy#245]
# Bug description

Not sure if its considered a bug, but here's the current situation:

We are trying to implement [Teleport](https://goteleport.com/) to manage the access to our clusters. The Teleport workflow is as follows: From the terminal server the request is forwarded to a teleport agent installed on the target Kubernetes cluster. The Agent then uses the given credentials from the Terminal server and impersonates further requests with given user/groups ([Details](https://goteleport.com/docs/kubernetes-access/getting-started/#deployment-overview)). No we obviously directly want to connect to the capsule-proxy for a nice user experience for our users.  To achieve that we directed the teleport agent to the capsule-proxy endpoint :

```
extraEnv:
        - name: KUBERNETES_SERVICE_PORT_HTTPS
          value: "9001"
        - name: KUBERNETES_SERVICE_PORT
          value: "9001"
        - name: KUBERNETES_PORT_9001_TCP
          value: "tcp://capsule-proxy.capsule-system.svc:9001"
        - name: KUBERNETES_PORT_9001_TCP_PROTO
          value: "tcp"
        - name: KUBERNETES_PORT_9001_TCP_ADDR
          value: "capsule-proxy.capsule-system.svc"
        - name: KUBERNETES_SERVICE_HOST
          value: "capsule-proxy.capsule-system.svc"
        - name: KUBERNETES_PORT
          value: "tcp://capsule-proxy.capsule-system.svc:9001"
        - name: KUBERNETES_PORT_9001_TCP_PORT
          value: "443"
extraVolumeMounts:
  - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
    name: kube-api-access-capsule
    readOnly: true
extraVolumes:
  - name: kube-api-access-capsule
    projected:
      sources:
        - serviceAccountToken:
            path: token 
        - configMap:
            items:
              - key: ca.crt
                path: ca.crt
            name: capsule-root-ca.crt
        - downwardAPI:
            items:
              - fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
                path: namespace
log:
        level: DEBUG


```
(Values for [teleport agent chart](https://github.com/gravitational/teleport/blob/master/examples/chart/teleport-kube-agent/README.md))

Great. That works. But now we are getting with every request the following error:

```
cannot retrieve user and group: the current user Oliver.Baehler@bedag.ch cannot impersonate the group company-group
```

The groups are random. It doesn't work for any group. That makes sense, since the user `Oliver.Baehler@bedag.ch` is not allowed to impersonate at all.

So what's happening: 

The SA `system:serviceaccount:teleport-agent:teleport-agent` is making a request with `Impersonate-User:  Oliver.Baehler@bedag.ch`  and `Impersonate-Group: *` with all my groups. The Impersonation is [detected & accepted] (https://github.com/clastix/capsule-proxy/blob/b57445a6debb9651e2ae9d40c4ed09eb2a717ce7/internal/request/http.go#L61) because the teleport SA can impersonate as [anyone](https://github.com/gravitational/teleport/blob/master/examples/chart/teleport-kube-agent/templates/clusterrole.yaml). But now comes the Problem, since the impersonation worked, we overwrite the username to perform the next request with the value of `Impersonate-User`:

https://github.com/clastix/capsule-proxy/blob/b57445a6debb9651e2ae9d40c4ed09eb2a717ce7/internal/request/http.go#L81

So now the impersonations of groups are attempted with `Oliver.Baehler@bedag.ch`: 

https://github.com/clastix/capsule-proxy/blob/b57445a6debb9651e2ae9d40c4ed09eb2a717ce7/internal/request/http.go#L93

Since that user does not have any permission to impersonate as anyone. Every Request will fail.

Now to ask the question: Should we really overwrite the username? I guess it makes sense but it also doesn't because from a client perspective I want to define the impersonation and i don't want the impersonation be resolved via the given Impersonating User. But I guess there's other reasons to do that.

As current Workaround we tell the teleport agent to impersonate as its on serviceaccount `Impersonate-User: system:serviceaccount:teleport-agent:teleport-agent`. Then it works as expected. But since we want to create permission on tenant basis with username reference, that's not gonna be a viable solution for the future.

Let's discuss if we can change this or if there's anything else we can do to workaround this.

# How to reproduce

Given above. For detailed instructions/showcase ping me on Slack

# Expected behavior

Given `Impersonate-Group` should perform SubjectAccessReviewSpec with the user making the Request, not with the user given in `Impersonate-User`.

# Logs

Not relevant.

# Additional context

- Capsule-Proxy version:`0.3.2`
