### ISSUE TITLE
unable to list nodes as a tenant owner

### ISSUE THREAD

**Issue by sagar-jadhav** [clastix/capsule-proxy#254]
# Bug description

As a tenant owner I am not able to list the nodes assigned to me.

# How to reproduce

As a cluster admin label the node as follows

```
kubectl label node localhost org=oil
```

As a cluster admin create the following tenant object:

```
apiVersion: capsule.clastix.io/v1beta2
kind: Tenant
metadata:
  name: oil
spec:
  owners:
    - kind: User
      name: alice
      proxySettings:
        - kind: Nodes
          operations:
            - List
  nodeSelector:
    org: oil
```

Login to the k8s cluster using tenant owner kubeconfig and run the following command:

```
kubectl get nodes

No resource found
```
# Expected behavior

As tenant owner I should be able to list the nodes with label `org: oil`

# Additional context

- Capsule-Proxy version: v0.3.2
- Helm Chart version: capsule-proxy-0.3.1
- Kubernetes version: Client Version: v1.23.16, Server Version: v1.22.7

# Notes

 I debugged the issue and found that [PR-239](https://github.com/clastix/capsule-proxy/pull/239) introduced this bug. Below pattern is incorrect:

```
"/api/v1/{nodes:[^/]+/?}"
```

Here mux will only capture the value of the "nodes" parameter as the portion of the URL that matches the pattern `[^/]+/?` So nodes is the name of the parameter and not the nodes as string. `[^/]+` signifies any number of character other than `/` and `/?` signifies that zero or one `/` in the URL. 

So when [mod.Path()](https://github.com/clastix/capsule-proxy/blob/501f017b4571ddbee9881e377d046c8ac5ffc18f/internal/webserver/webserver.go#L228) method is invoked for namespace module with path **/api/v1/{namespaces:[^/]+/?}** a route is registered which matches with the below pattern

```
/api/v1/somecharacters
```

for e.g. /api/v1/nodes, /api/v1/namespace etc

So all calls starting with `/api/v1/somecharacters` pattern is handled by the namespace handler because of **/api/v1/{namespaces:[^/]+/?}** pattern. 

I changed the pattern from `/api/v1/{namespaces:[^/]+/?}` to `/api/v1/{endpoint:namespaces/?}` and able to resolve the issue. Here endpoint is name of the parameter and `namespaces/?` signifies that word should start with namespaces string and should or should not end with `/`
