### ISSUE TITLE
Certificate valid only for ingress host names with cert-manager

### ISSUE THREAD

**Issue by maxgio92** [clastix/capsule-proxy#262]
When installing the proxy with Helm configuring the proxy's x509 certificates generation through Cert Manager with an external CA, the generated Certificate is valid only for the ingress hosts, even with setting `ingress.enabled=false`.

# How to reproduce

Template the Helm release by running:

```shell
helm template capsule-proxy clastix/capsule-proxy --set certManager.generateCertificates=true --set certManager.externalCA.enabled=true --set certManager.externalCA.secretName=pippo-ca --set certManager.issuer.kind=Issuer --namespace capsule-system --set ingress.enabled=false
```

the templated Cert Manager `Certificate` resource is something like:

```yaml
# Source: capsule-proxy/templates/certmanager.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: capsule-proxy-serving-cert
spec:
  dnsNames:
  - kube.clastix.io
  issuerRef:
    kind: Issuer
    name: capsule-proxy-ca-issuer
  secretName: capsule-proxy
  subject:
    organizations:
      - clastix.io
```

# Expected behavior

The following DNS SANs in the `Certificate`:
- `capsule-proxy`
- `capsule-proxy.<helm_release_namespace>.svc`

ignoring the host names when disabled the `Ingress` resource. 
Something like this:

```yaml
# Source: capsule-proxy/templates/certmanager.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: capsule-proxy-serving-cert
spec:
  dnsNames:
  - capsule-proxy
  - capsule-proxy.capsule-system.svc
  issuerRef:
    kind: Issuer
    name: capsule-proxy-ca-issuer
  secretName: capsule-proxy
  subject:
    organizations:
      - clastix.io
```

# Logs

NA

# Additional context

- Capsule-Proxy version: 0.3.3
- Helm Chart version: 0.3.6
- Kubernetes version: 1.24.10
