### ISSUE TITLE
Tenant owner can list the namespace not managed by Capsule

### ISSUE THREAD

**Issue by sagar-jadhav** [clastix/capsule-proxy#287]
# Bug description

As a Tenant Owner I am able to list the namespace not managed by Capsule.

# How to reproduce

Create a Tenant `oil` as a cluster admin

```
apiVersion: capsule.clastix.io/v1beta2
kind: Tenant
metadata:
  name: oil
spec:
  owners:
  - name: alice
    kind: User
```
Create a namespace `db` as a cluster admin

```
kubectl create ns db
kubectl label ns name=db
```
Create a RoleBinding `admin` as a cluster admin

```
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin
  namespace: db
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: alice
```
**Note:** Issue is not tied to any Role you can refer any Role or ClusterRole in the RoleBinding but in subject user needs to be Alice.

Create a namespace `oil-frontend` as a Alice user

```
kubectl create ns oil-frontend
```
List the namespace as a Alice user

```
kubectl get ns

NAME           STATUS   AGE
db             Active   3h
oil-frontend   Active   1h
```

# Expected behaviour

As a Tenant owner I should only see the namespaces managed by Capsule. In the above e.g. only `oil-frontend` should be listed.

# Additional context

- Helm Chart version: v0.4.2
