### ISSUE TITLE
Unable to exec inside a pod when using capsule-proxy

### ISSUE THREAD

**Issue by GlassOfWhiskey** [clastix/capsule-proxy#51]
# Bug Description

When trying to `kubectl exec` into a Pod through the `capsule-proxy`, the action fails with a `Error from server:` message (no error details are reported). This happens both for interactive and non-interactive execs.

Neither capsule-proxy nor envoy logs report errors, so I am not able to figure out if this is a Contour issue or a Capsule issue. Maybe only some additional configuration is missing somewhere, preventing websocket connections to work properly.

# How to reproduce

1. Create a kubeconfig file accessing the cluster through the capsule proxy
2. Create a test pod using `kubectl run --image=alpine test`
3. Try to exec inside the container with `kubectl exec -it test -- sh`

# Additional context
Kubernetes v1.20.2
Capsule Proxy Standalone Helm Chart version 0.1.0 with the following values

```yaml
options:
  capsuleUserGroup: tenant-owners
  oidcUsernameClaim: email

# Enable HTTPS Ingress with Contour
ingress:
  enabled: true
  hosts:
    - host: kubernetes.test-odh.di.unito.it
      paths: ["/"]
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-cluster-issuer
    ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/ingress.class: contour
    kubernetes.io/tls-acme: "true"
  tls:
    - hosts:
        - kubernetes.test-odh.di.unito.it
      secretName: kubernetes.test-odh.di.unito.it-tls

# Disable autoscaling
autoscaling:
  enabled: false

# Fix the number of replicas to 3
replicaCount: 3
```

**Comment by bsctl** [comment]
@GlassOfWhiskey thanks for reporting this. Actually we use `capsule-proxy` exposed with HAProxy Ingress Controller similar to [this](https://github.com/clastix/capsule/blob/master/docs/proxy/standalone.md#standalone-installation) and we can exec into the containers.

Please, try to increase the log level by `options.logLevel` option in Helm chart values and let us know.

**Comment by MaxFedotov** [comment]
Same with ingress-nginx - we are able to exec into containers

**Comment by GlassOfWhiskey** [comment]
It was a Contour problem, which I solved thanks to your help (knowing that with other IngressControllers everything works correctly helped me in isolating the problem).

The problem was that, as correctly mentioned in the documentation, Capsule proxy needs TLS Passthrough, while I configured it in termination mode. Configuring TLS Passthrough solved the issue.

A note for other people that could face my situation. It turns out that Contour does not support the `ingress.kubernetes.io/ssl-passthrough: 'true'` annotation on the Ingress resource. TLS Passthrough can only be enabled using `HTTPProxy` resources, which are Contour-specific. I solved the issue by manually deploying the certificate and the HTTPProxy as follows

```yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kubernetes.test-odh.di.unito.it-tls
  namespace: capsule-system
spec:
  dnsNames:
  - kubernetes.test-odh.di.unito.it
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-cluster-issuer
  secretName: capsule-proxy
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: capsule-proxy
  namespace: capsule-system
spec:
  virtualhost:
    fqdn: kubernetes.test-odh.di.unito.it
    tls:
      passthrough: true
  tcpproxy:
    services:
    - name: capsule-proxy
      port: 9001
```
and then deploying the Helm chart with the following values (note that w.r.t. the original version I disabled the Ingress generation and enabled SSL management on the `capsule-proxy` Pod)

```yaml
# Configure proxy options
options:
  capsuleUserGroup: tenant-owners
  enableSSL: true
  oidcUsernameClaim: email

# Disable autoscaling
autoscaling:
  enabled: false

# Fix the number of replicas to 3
replicaCount: 3
```
